version: '3.4'

services:
  komm-rein.api:
    image: ${DOCKER_REGISTRY-}kommreinapi
    build:
      context: .
      dockerfile: komm-rein.api/Dockerfile
    depends_on:
       - db
       - komm-rein.oidc
  komm-rein.oidc:
    image: ${DOCKER_REGISTRY-}kommreinoidc
    build:
      context: .
      dockerfile: komm-rein.oidc/Dockerfile
  db:
    image: postgres