version: '3.4'
services:
  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db-backub:/var/backup
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: komm_rein
    ports:
      - "5432:5432"